language: python
python: 
  - "3.6"

install: 
  - "pip install -r requirements.txt"

script: 
  - pytest
  
cache: pip
deploy: 
  distributions: "sdist bdist_wheel"
  password: $PASSWD
  provider: pypi
  true: 
    tags: true
  user: bestony
