language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
cache:pip
deploy:
  provider: pypi
  user: bestony
  distributions: sdist bdist_wheel
  password: $PASSWD
  on:
    tags: true
